using System.Globalization;

namespace OASX.WPF.Services;

/// <summary>
/// Provides runtime translations for both built-in keys (extracted from the Flutter i18n files)
/// and server-supplied additional translations fetched via GET /home/additional_translate.
/// Usage: LocalizationService.Instance.Translate("key")
/// </summary>
public sealed class LocalizationService
{
    private static LocalizationService? _instance;
    public static LocalizationService Instance => _instance ??= new();

    private readonly Dictionary<string, string> _zhCn;
    private readonly Dictionary<string, string> _enUs;
    private string _currentLanguage = "zh-CN";

    /// <summary>Fires whenever the active language changes.</summary>
    public event Action? Changed;

    public string CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            if (_currentLanguage == value) return;
            _currentLanguage = value;
            Changed?.Invoke();
        }
    }

    public LocalizationService()
    {
        _zhCn = new Dictionary<string, string>(_builtInZhCn, StringComparer.OrdinalIgnoreCase);
        _enUs = new Dictionary<string, string>(_builtInEnUs, StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Returns the translation for <paramref name="key"/> in the current language,
    /// or falls back to capitalising the key's words if no translation is found.
    /// </summary>
    public string Translate(string key)
    {
        if (string.IsNullOrEmpty(key)) return key;
        var dict = _currentLanguage == "zh-CN" ? _zhCn : _enUs;
        if (dict.TryGetValue(key, out var val) && !string.IsNullOrEmpty(val)) return val;
        // Fallback: replace underscores with spaces, title-case (matches Flutter convertCnToUsMap)
        return CultureInfo.InvariantCulture.TextInfo.ToTitleCase(key.Replace('_', ' '));
    }

    /// <summary>Merges extra translations received from the server.</summary>
    public void MergeTranslations(string lang, Dictionary<string, string> extra)
    {
        var dict = lang == "zh-CN" ? _zhCn : _enUs;
        foreach (var (k, v) in extra)
            dict[k] = v;
    }

    /// <summary>Returns the full Chinese dictionary (for pushing to the OAS server).</summary>
    public Dictionary<string, string> GetChineseDictionary() => new(_zhCn);

    // -------------------------------------------------------------------------
    // Built-in translations extracted from lib/config/translation/i18n_cn.dart
    // and lib/config/translation/i18n_us.dart
    // -------------------------------------------------------------------------
    
        private static readonly Dictionary<string, string> _builtInZhCn = new()
        {
            [@"No arguments available."] = @"暂无参数。",
            [@"Failed to load arguments."] = @"加载参数失败。",
            [@"About"] = @"关于",
            [@"AbyssShadows"] = @"狭间暗域",
            [@"Activity Task"] = @"限时活动",
            [@"ActivityShikigami"] = @"当期爬塔",
            [@"Add new config"] = @"添加新配置",
            [@"Any"] = @"全部",
            [@"Are you sure kill OAS server"] = @"真的要关闭脚本服务吗",
            [@"Are you sure to delete"] = @"你确定要删除",
            [@"AreaBoss"] = @"地域鬼王",
            [@"Attack_60"] = @"启用攻打60级",
            [@"Author"] = @"作者",
            [@"BondlingFairyland"] = @"契灵之境",
            [@"Cancel"] = @"取消",
            [@"Change Language"] = @"切换语言",
            [@"Change Theme"] = @"切换主题",
            [@"Clear Log"] = @"清空日志",
            [@"Click to download"] = @"点击下载",
            [@"CollectiveMissions"] = @"集体任务",
            [@"CombatTime_enable"] = @"启用智能时间",
            [@"Config update tip"] = @"当前脚本正在运行，请停止后再修改",
            [@"Confirm"] = @"确定",
            [@"Copy from existing config"] = @"复制已有配置",
            [@"Copy success"] = @"复制成功",
            [@"Current Version"] = @"当前版本",
            [@"Current branch"] = @"当前分支",
            [@"Daily Task"] = @"日常任务",
            [@"DailyTrifles"] = @"每日琐事",
            [@"Days"] = @"日",
            [@"Delegation"] = @"式神委派",
            [@"Delete"] = @"删除",
            [@"DemonEncounter"] = @"逢魔之时",
            [@"DemonRetreat"] = @"首领退治",
            [@"Dokan"] = @"道馆",
            [@"Duel"] = @"斗技",
            [@"DyeTrials"] = @"灵染试炼",
            [@"EternitySea"] = @"永生之海",
            [@"EvoZone"] = @"觉醒副本",
            [@"ExperienceYoukai"] = @"经验妖怪",
            [@"Exploration"] = @"探索",
            [@"FallenSun"] = @"日轮之陨",
            [@"Find New Version"] = @"发现新版本",
            [@"Find OAS new version"] = @"发现OAS新版本",
            [@"FindJade"] = @"寻找协作任务",
            [@"FloatParade"] = @"花车巡游",
            [@"FoodAndSushi"] = @"食协+体协",
            [@"FoodOnly"] = @"仅食协",
            [@"FrogBoss"] = @"对弈竞猜",
            [@"GlobalGame"] = @"全局配置",
            [@"GoldAndFood"] = @"金币+食协",
            [@"GoldAndFoodAndSushi"] = @"金币+食协+体协",
            [@"GoldAndJade"] = @"金币和勾协",
            [@"GoldAndJadeAndFood"] = @"金币+勾协+食协",
            [@"GoldAndJadeAndSushi"] = @"金币+勾协+体协",
            [@"GoldAndSushi"] = @"金币+体协",
            [@"GoldOnly"] = @"仅金币",
            [@"GoldYoukai"] = @"金币妖怪",
            [@"GoryouRealm"] = @"御灵之境",
            [@"Guild"] = @"阴阳寮",
            [@"GuildBanquet"] = @"寮宴会",
            [@"HeroTest"] = @"英杰试炼",
            [@"Home"] = @"主页",
            [@"Hours"] = @"时",
            [@"Hunt"] = @"狩猎战",
            [@"Hyakkiyakou"] = @"百鬼夜行",
            [@"Install OAS failure"] = @"安装OAS失败",
            [@"Install OAS from GitHub"] = @"从GitHub安装OAS",
            [@"Install OAS from local"] = @"这将会从Github上下载并解压，请保持网络稳定，同时将会清空该目录",
            [@"Install OAS success"] = @"安装OAS成功",
            [@"JadeAndFood"] = @"勾协+食协",
            [@"JadeAndFoodAndSushi"] = @"勾协+食协+体协",
            [@"JadeAndSushi"] = @"勾协+体协",
            [@"JadeOnly"] = @"仅勾协",
            [@"KekkaiActivation"] = @"结界挂卡",
            [@"KekkaiUtilize"] = @"结界蹭卡",
            [@"Kill OAS server"] = @"结束OAS服务",
            [@"Kill server failure"] = @"关闭服务失败",
            [@"Kill server success"] = @"关闭服务成功",
            [@"KittyShop"] = @"猫咪铺子",
            [@"Latest Version"] = @"最新版本",
            [@"Liver Emperor Exclusive"] = @"肝帝专属",
            [@"Local repo"] = @"本地仓库",
            [@"Log"] = @"日志",
            [@"Log out"] = @"退出登录",
            [@"Login"] = @"登录",
            [@"MemoryScrolls"] = @"绘卷",
            [@"MetaDemon"] = @"超鬼王",
            [@"Minutes"] = @"分",
            [@"Months"] = @"月",
            [@"MysteryShop"] = @"神秘商店",
            [@"Name already exists"] = @"名称已存在",
            [@"Name cannot be Home"] = @"名称非法",
            [@"Name cannot be empty"] = @"名称不能为空",
            [@"Network Connect Timeout"] = @"连接超时",
            [@"Network Error"] = @"网络错误",
            [@"Network Error Code"] = @"错误代码",
            [@"Network Not Found"] = @"找不到网络",
            [@"Network Unknown Error"] = @"网络未知错误",
            [@"New name"] = @"新名称",
            [@"Nian"] = @"年兽",
            [@"No Data"] = @"暂无数据",
            [@"NoInvite"] = @"不邀请",
            [@"Notify Config"] = @"推送配置",
            [@"Notify Content"] = @"发送内容",
            [@"Notify Failed"] = @"推送失败",
            [@"Notify Help"] = @"请翻阅文档[消息推送]进行填写相关配置",
            [@"Notify Send"] = @"点击测试",
            [@"Notify Success"] = @"推送成功",
            [@"Notify Test"] = @"推送测试",
            [@"Notify Title"] = @"发送主题",
            [@"Now install OAS"] = @"现在安装OAS",
            [@"OAS latest version"] = @"OAS已是最新版本",
            [@"Orochi"] = @"八岐大蛇",
            [@"Overview"] = @"总览",
            [@"Pendings"] = @"队列中",
            [@"Pets"] = @"小猫咪",
            [@"Project Statement"] = @"开源软件",
            [@"Quiz"] = @"智力竞赛",
            [@"RealmRaid"] = @"个人突破",
            [@"Remote repo"] = @"远程仓库",
            [@"Rename"] = @"重命名",
            [@"Restart"] = @"重启",
            [@"RichMan"] = @"大富翁",
            [@"Root path incorrect"] = @"无法识别的根目录，你可能没有正确安装OAS",
            [@"Root path incorrect help"] = @"正确识别为OAS的根目录",
            [@"Running"] = @"运行中",
            [@"RyouToppa"] = @"寮突破",
            [@"Script"] = @"脚本",
            [@"Seconds"] = @"秒",
            [@"Secret"] = @"秘闻副本",
            [@"Select root path server"] = @"选择文件夹",
            [@"Service root path"] = @"OAS根目录",
            [@"Service root path help"] = @"OASX跟OAS是两个不同的东西, 不要搞混，不要放在同一个目录下, 不要有空格的, 不要有中文的, 也不要路径过长的",
            [@"Setting"] = @"设置",
            [@"Setting saved"] = @"设置已保存",
            [@"Setup deploy"] = @"服务启动配置",
            [@"Setup log"] = @"服务启动日志",
            [@"SixRealms"] = @"六道之门",
            [@"Sougenbi"] = @"业原火",
            [@"Soul Zones"] = @"御魂副本",
            [@"SoulsTidy"] = @"御魂整理",
            [@"Submit info"] = @"提交信息",
            [@"Submit time"] = @"提交时间",
            [@"SushiOnly"] = @"仅体协",
            [@"Tako"] = @"石距",
            [@"TalismanPass"] = @"花合战",
            [@"Task Setting"] = @"设置",
            [@"TaskList"] = @"任务列表",
            [@"Tip"] = @"提示",
            [@"Tool"] = @"工具",
            [@"Tools"] = @"工具",
            [@"TrueOrochi"] = @"真八岐大蛇",
            [@"Updater"] = @"更新器",
            [@"Waitings"] = @"等待中",
            [@"WantedQuests"] = @"悬赏封印",
            [@"Weekly Task"] = @"每周任务",
            [@"WeeklyTrifles"] = @"每周琐事",
            [@"Weeks"] = @"星期",
            [@"Years"] = @"年",
            [@"abyss_shadows_combat_time"] = @"狭间暗域战斗时间配置",
            [@"abyss_shadows_time"] = @"狭间暗域时间配置",
            [@"accept"] = @"全部接受",
            [@"accept_invitation_complete_now"] = @"接受协作后立即去完成",
            [@"accept_invitation_complete_now_help"] = @"防止两小时不做被对方取消，默认开启",
            [@"account"] = @"账号",
            [@"account_alias"] = @"账号别名",
            [@"account_alias_help"] = @"防止文字识别出错的产物,多个别名用#分隔.例如188****8888，被识别为1BB****BBBB或被识别为188****BBBB等等，就填“1BB****BBBB#188****BBBB"",更多详情请见代码目录FindJade下的README.md",
            [@"account_help"] = @"登录时使用的手机号/邮箱等，在登录时，界面显示什么，就填什么。例如手机账号显示“188****8888"",就填带星号的",
            [@"activation_config"] = @"结界挂卡",
            [@"active_souls_clean"] = @"结束爬塔后启动御魂整理",
            [@"active_souls_clean_help"] = @"防止御魂溢出",
            [@"activity_toggle"] = @"挂完活动次数后切换到体力模式",
            [@"activity_toggle_help"] = @"该设置只有是设定为活动次数时有效",
            [@"adb_restart"] = @"在检测不到设备的时候尝试重启adb",
            [@"adb_restart_help"] = @"",
            [@"anti_detect_click_fixed_random_area"] = @"点击固定随机区域",
            [@"anti_detect_click_fixed_random_area_help"] = @"防封使用固定的随机区域进行随机点击, 若不启用将自动识别当前画面中的最大纯色区域作为随机点击区域",
            [@"ap"] = @"体力",
            [@"ap100_limit"] = @"100体爬塔的最大次数",
            [@"ap100_limit_help"] = @"",
            [@"ap_100"] = @"体力100",
            [@"ap_game_max"] = @"活动每日使用体力挑战的最大次数",
            [@"ap_game_max_help"] = @"保持默认300即可",
            [@"ap_help"] = @"默认买两次不够就不买",
            [@"ap_limit"] = @"",
            [@"ap_limit_help"] = @"",
            [@"ap_mode"] = @"挂体力模式",
            [@"ap_mode_help"] = @"设置是挂活动的次数(ap_activity)还是游戏的体力(ap_game)",
            [@"apple_or_android"] = @"苹果/安卓",
            [@"apple_or_android_help"] = @"勾选为安卓，不勾选苹果",
            [@"attack_count_config"] = @"攻击数量设置",
            [@"attack_date"] = @"记录时间",
            [@"attack_date_help"] = @"剩余攻击次数的时间有效期,即 该时间剩余攻击次数为 .一般情况下，此值无须手动修改",
            [@"attack_dokan_master"] = @"攻打馆主策略",
            [@"attack_dokan_master_help"] = @"僵尸寮比较有用,一般的保持TWO_TWO即可.两次道馆，ONE/TWO表示打馆主的第一/第二阵容。僵尸寮建议ZERO_TWO",
            [@"attack_number"] = @"通关次数",
            [@"auto_close_exploration"] = @"启用自动关闭探索",
            [@"auto_contribute_memoryscrolls"] = @"启用自动捐献绘卷",
            [@"auto_finish_exploration"] = @"自动结束探索",
            [@"auto_rotate"] = @"自动添加候补式神",
            [@"auto_rotate_help"] = @"",
            [@"auto_switch_soul"] = @"是否启用",
            [@"auto_switch_soul_help"] = @"如果你有5套独立阵容，那么这一项无需开启,否则你可以开启这一项御魂轮换（探查是默认不需要轮换的）",
            [@"auto_switch_soul_orochi_help"] = @"各层使用独立的御魂预设",
            [@"auto_tea"] = @"自动喝茶",
            [@"auto_tea_help"] = @"",
            [@"azure_basan_switch"] = @"设置火灵的御魂装配分组",
            [@"azure_basan_switch_help"] = @"",
            [@"ban_name"] = @"填写第五手式神名称",
            [@"ban_name_help"] = @"",
            [@"battle_config"] = @"战斗设置",
            [@"battle_mode"] = @"战斗模式",
            [@"battle_mode_help"] = @"",
            [@"battle_priority"] = @"打怪优先级",
            [@"battle_priority_help"] = @"默认为 挑战 > 秘闻 > 探索",
            [@"before_end"] = @"强制设定悬赏刷新前 X 分钟执行",
            [@"before_end_frog"] = @"在本次结束前 X 分钟下注",
            [@"before_end_frog_help"] = @"",
            [@"before_end_help"] = @"默认[00:00:00]表示不使用这个功能，不可取负值，建议最后一小时才执行悬赏[01:00:00]",
            [@"best_demon_boss_config"] = @"极逢魔配置",
            [@"best_demon_gashadokuro"] = @"极荒骷髅",
            [@"best_demon_gashadokuro_select"] = @"极荒骷髅",
            [@"best_demon_kiryou_select"] = @"极鬼灵歌姬",
            [@"best_demon_kiryou_utahime"] = @"极鬼灵歌姬",
            [@"best_demon_kiryou_utahime_supplementary"] = @"极鬼灵歌姬补充",
            [@"best_demon_namazu"] = @"极地震鲶",
            [@"best_demon_namazu_select"] = @"极地震鲶",
            [@"best_demon_shinkirou"] = @"极蜃气楼",
            [@"best_demon_shinkirou_select"] = @"极蜃气楼",
            [@"best_demon_soul_config"] = @"极逢魔御魂配置",
            [@"best_demon_tsuchigumo"] = @"极土蜘蛛",
            [@"best_demon_tsuchigumo_select"] = @"极土蜘蛛",
            [@"bird_feather"] = @"鸟之羽",
            [@"bird_feather_help"] = @"50体力->20片大蛇的逆鳞",
            [@"black_daruma"] = @"御行达摩",
            [@"black_daruma_fragment"] = @"御行达摩碎片",
            [@"black_daruma_scrap"] = @"黑蛋碎片",
            [@"black_daruma_scrap_help_honor"] = @"默认买两个",
            [@"bondling_config"] = @"契灵之境",
            [@"bondling_mode"] = @"设置战斗策略",
            [@"bondling_mode_help"] = @"",
            [@"bondling_stone"] = @"鸣契石",
            [@"bondling_stone_class"] = @"使用契石时选择召唤类型",
            [@"bondling_stone_class_help"] = @"",
            [@"bondling_stone_enable"] = @"是否使用契石召唤契灵",
            [@"bondling_stone_enable_help"] = @"会优先开启契石，之后才是探查",
            [@"bondling_stone_help"] = @"可选[0~10]",
            [@"bondling_switch_soul"] = @"契灵之境切换御魂",
            [@"bondlings"] = @"契忆商店",
            [@"boss"] = @"鬼王",
            [@"boss_combat_time"] = @"首领战斗时间",
            [@"boss_limit"] = @"",
            [@"boss_limit_help"] = @"",
            [@"boss_number"] = @"鬼王挑战数量",
            [@"boss_reward"] = @"查找当日悬赏鬼王",
            [@"boss_reward_help"] = @"",
            [@"box_ap_enable"] = @"顺路收取体力盒子",
            [@"box_ap_enable_help"] = @"必选项",
            [@"box_buy_config"] = @"逢魔宝箱配置",
            [@"box_buy_sushi"] = @"启用购买体力宝箱",
            [@"box_exp_enable"] = @"顺路收取经验盒子",
            [@"box_exp_enable_help"] = @"必选项",
            [@"box_exp_waste"] = @"从盒子提取经验时浪费一部分",
            [@"box_exp_waste_help"] = @"某些时候寄养上存在满级的式神，收取经验盒子时会有提示，对于挂机玩家这点经验微不足道。如果不使能这一选项，将跳过收取经验盒子",
            [@"broken_amulet"] = @"破碎的咒符",
            [@"broker"] = @"broker",
            [@"broker_help"] = @"",
            [@"buff_enable"] = @"开启加成",
            [@"buff_exp_100_click"] = @"开启经验加成100%",
            [@"buff_exp_50_click"] = @"开启经验加成50%",
            [@"buff_gold_100_click"] = @"开启金币加成100%",
            [@"buff_gold_50_click"] = @"开启金币加成50%",
            [@"buy_sale_ticket"] = @"兑换一百张寄售券",
            [@"buy_sale_ticket_help"] = @"等凑够了再去换",
            [@"buy_sushi_count"] = @"购买体力数量",
            [@"ca"] = @"ca",
            [@"ca_help"] = @"",
            [@"card_rule"] = @"放卡规则",
            [@"card_rule_help"] = @"详情看文档",
            [@"cat_boss"] = @"猫老大",
            [@"cat_boss_help"] = @"300体力->四星白蛋",
            [@"celeb_battle"] = @"开启名士斗技",
            [@"celeb_battle_help"] = @"",
            [@"challenge_pass"] = @"挑战券",
            [@"challenge_pass_help"] = @"可选[0~10]",
            [@"character"] = @"角色名",
            [@"character_help"] = @"小号-庭院左上角显示的那个，鉴于文字识别准确性不足，角色名搞点容易识别的",
            [@"charisma"] = @"[杂货铺]魅力值购买",
            [@"choose_rarity"] = @"自动添加候补式神种类",
            [@"choose_rarity_help"] = @"",
            [@"combat_screenshot_interval"] = @"战斗中放慢截图速度至 X 秒一张",
            [@"conf_threshold"] = @"置信度阈值",
            [@"conf_threshold_help"] = @"用来筛选检测结果,置信度得分越高，表示模型越确信该框中包含目标",
            [@"consignment"] = @"寄售屋",
            [@"continuous_learning"] = @"回馈学习",
            [@"continuous_learning_help"] = @"将会保存有价值的图片在""./log/hya""，应当将这些图片上传到群文件，用于优化模型~比心( ´ ▽ ` ).｡ｏ♡",
            [@"control_method"] = @"模拟器控制方案",
            [@"control_method_help"] = @"速度: window_message ~= minitouch > Hermit >>> uiautomator2 ~= ADB
控制方式是模拟人类的速度，也不是越快越好 使用(window_message)会偶尔出现失效的情况",
            [@"cooperation_only"] = @"只完成协作任务",
            [@"cooperation_only_help"] = @"仅在存在 邀请特定人员 时生效",
            [@"cooperation_type"] = @"邀请好友协作类型",
            [@"cooperation_type_help"] = @"仅在存在 邀请特定人员 时生效",
            [@"costume_battle_1"] = @"雅乐之邦",
            [@"costume_battle_2"] = @"蝶寻花踪",
            [@"costume_battle_3"] = @"凛霜寒雪",
            [@"costume_battle_4"] = @"春缕含青",
            [@"costume_battle_5"] = @"祥夜幽芳",
            [@"costume_battle_6"] = @"桂馥金秋",
            [@"costume_battle_7"] = @"笼梦之境",
            [@"costume_battle_8"] = @"藏金台阁",
            [@"costume_battle_9"] = @"莲华圣域",
            [@"costume_battle_default"] = @"默认",
            [@"costume_battle_type"] = @"战斗主题",
            [@"costume_battle_type_help"] = @"",
            [@"costume_config"] = @"游戏装饰自定义",
            [@"costume_main"] = @"初语谧景",
            [@"costume_main_1"] = @"织梦莲庭",
            [@"costume_main_10"] = @"望月幽庭",
            [@"costume_main_11"] = @"鏖刀禁府",
            [@"costume_main_12"] = @"龙吟溯玉",
            [@"costume_main_13"] = @"云景阆苑",
            [@"costume_main_2"] = @"琼夜淬光",
            [@"costume_main_3"] = @"烬夜韶阁",
            [@"costume_main_4"] = @"笔墨山河",
            [@"costume_main_5"] = @"枫色秋庭",
            [@"costume_main_6"] = @"暖池青苑",
            [@"costume_main_7"] = @"盛夏幽庭",
            [@"costume_main_8"] = @"远海航船",
            [@"costume_main_9"] = @"结缘神社",
            [@"costume_main_type"] = @"庭院皮肤",
            [@"costume_main_type_help"] = @"宠物屋不可用：[暖池青苑]、[枫色秋庭]",
            [@"costume_realm_1"] = @"鬼灵咒符",
            [@"costume_realm_2"] = @"狐梦之乡",
            [@"costume_realm_3"] = @"编心织忆",
            [@"costume_realm_4"] = @"花海繁生",
            [@"costume_realm_5"] = @"5555",
            [@"costume_realm_default"] = @"妖扇结界",
            [@"costume_realm_type"] = @"结界皮肤",
            [@"costume_realm_type_help"] = @"测试阶段",
            [@"costume_shikigami_1"] = @"妙音空境",
            [@"costume_shikigami_2"] = @"缘台樱垂",
            [@"costume_shikigami_3"] = @"启程之刻",
            [@"costume_shikigami_4"] = @"冥夜游火",
            [@"costume_shikigami_5"] = @"契光水境",
            [@"costume_shikigami_default"] = @"静栖走廊",
            [@"costume_shikigami_type"] = @"幕间",
            [@"costume_shikigami_type_help"] = @"就是式神录",
            [@"costume_sign_default"] = @"默认",
            [@"costume_sign_type"] = @"签到主题",
            [@"costume_sign_type_help"] = @"",
            [@"costume_theme_default"] = @"伊始之卷",
            [@"costume_theme_type"] = @"主题",
            [@"costume_theme_type_help"] = @"庭院最右下角的展开按钮",
            [@"craft_essence_help"] = @"只会把一星合成二星",
            [@"current_exploration_times"] = @"current_exploration_times",
            [@"current_success"] = @"本周已经挑战成功的次数",
            [@"current_success_help"] = @"请不要手动修改这一项，是为了给机器计数的，机器会自动修改",
            [@"custom_run_time"] = @"自定义运行时间",
            [@"custom_run_time_friday"] = @"自定义周五运行时间",
            [@"custom_run_time_saturday"] = @"自定义周六运行时间",
            [@"custom_run_time_sunday"] = @"自定义周日运行时间",
            [@"daily_attack_count"] = @"每日道馆次数",
            [@"daily_attack_count_help"] = @"僵尸寮比较有用，正常的保持2即可.每天要打两次道馆的，两次道馆时间间隔由 调度器中 [失败后设定经过X时间后执行]确定",
            [@"day_1"] = @"第一次运行日期",
            [@"day_2"] = @"第二次运行日期",
            [@"debug_config"] = @"调试配置",
            [@"default_invite"] = @"战斗结束后勾选默认邀请",
            [@"default_invite_help"] = @"",
            [@"default_invite_type"] = @"协作任务类型",
            [@"default_invite_type_help"] = @"该账号需要的协作任务类型",
            [@"delay_date"] = @"强制日期间隔",
            [@"delay_date_help"] = @"启用上方强制设定执行时间时，自定义几天后强制执行，默认一天后即第二天",
            [@"delegation_config"] = @"委派",
            [@"demon_class"] = @"首领御魂类型",
            [@"demon_class_help"] = @"不支持多个首领",
            [@"demon_gashadokuro"] = @"荒骷髅",
            [@"demon_kiryou_utahime"] = @"鬼灵歌姬",
            [@"demon_kiryou_utahime_supplementary"] = @"鬼灵歌姬补充",
            [@"demon_namazu"] = @"地震鲶",
            [@"demon_nightly_aramitama"] = @"夜荒魂",
            [@"demon_oboroguruma"] = @"胧车",
            [@"demon_position"] = @"首领御魂号位",
            [@"demon_position_help"] = @"不支持多号位",
            [@"demon_retreat_time"] = @"首领退治时间",
            [@"demon_shinkirou"] = @"蜃气楼",
            [@"demon_soul_config"] = @"御魂配置",
            [@"demon_souls"] = @"首领御魂",
            [@"demon_souls_help"] = @"可选[0~50]",
            [@"demon_tsuchigumo"] = @"土蜘蛛",
            [@"device"] = @"模拟器设置",
            [@"dokan_attack_priority"] = @"攻击优先顺序",
            [@"dokan_attack_priority_help"] = @"见习=0,初级=1...",
            [@"dokan_auto_cheering_while_cd"] = @"失败CD后自动加油",
            [@"dokan_auto_cheering_while_cd_help"] = @"",
            [@"dokan_config"] = @"道馆配置",
            [@"dokan_score_help"] = @"赏金与人数的比值，查找道馆时，最大道馆系数，只开启低于此系数的道馆",
            [@"duel_celeb_config"] = @"名士斗技",
            [@"duel_config"] = @"自动斗技",
            [@"eleven_switch"] = @"十一层御魂配置",
            [@"eleven_switch_help"] = @"基于数字索引，悲鸣",
            [@"elite_combat_time"] = @"精英战斗时间",
            [@"emergency"] = @"突发检测",
            [@"emulator_window_minimize"] = @"启用模拟器窗口最小化",
            [@"emulatorinfo_name"] = @"模拟器名称",
            [@"emulatorinfo_name_help"] = @"示例: MuMuPlayer-12.0-0, 若不清楚请查阅文档",
            [@"emulatorinfo_path"] = @"模拟器路径",
            [@"emulatorinfo_path_help"] = @"举例：""E:\\ProgramFiles\\MuMuPlayer-12.0\\shell\\MuMuPlayer.exe""",
            [@"emulatorinfo_type"] = @"模拟器类型",
            [@"emulatorinfo_type_help"] = @"选择你使用的模拟器类型",
            [@"en-US"] = @"English",
            [@"enable"] = @"启用该功能",
            [@"enable_ap"] = @"体力",
            [@"enable_help"] = @"将这个任务加入调度器",
            [@"enable_jade"] = @"永久勾玉卡",
            [@"enable_mail"] = @"邮件",
            [@"enable_sign"] = @"每日签到",
            [@"enable_sign_999"] = @"签到999天后的签到福袋",
            [@"enable_soul"] = @"御魂或者觉醒加成",
            [@"enable_switch_by_name"] = @"通过OCR来切换御魂预设",
            [@"enable_switch_by_name_help"] = @"这是切换御魂的另一种方式，对比上方的方式而言支持更多的预设，但是同样的你还确保预设队伍是锁定状态的",
            [@"error"] = @"出错设置",
            [@"eternity_sea_config"] = @"永生之海",
            [@"evo_zone_config"] = @"觉醒副本",
            [@"exchange_before"] = @"收取经验前更换下来满级的式神",
            [@"exchange_before_help"] = @"必选项",
            [@"exchange_max"] = @"收取经验后更换下来满级的式神",
            [@"exchange_max_help"] = @"必选项",
            [@"execute_update"] = @"手动更新",
            [@"exit_four"] = @"当进攻到左上角第一个的时候先退四次再进攻",
            [@"exit_four_help"] = @"为了支持打九退四，保证稳定57级",
            [@"exp_100_buff_enable_help"] = @"启用100%经验加成",
            [@"exp_50_buff_enable_help"] = @"启用50%经验加成",
            [@"experience_youkai"] = @"经验妖怪",
            [@"exploration_config"] = @"探索副本",
            [@"exploration_level"] = @"探索章节",
            [@"exploration_level_help"] = @"",
            [@"extreme_notify"] = @"最高等级鬼王不打而是发送通知",
            [@"extreme_notify_help"] = @"",
            [@"failure_interval"] = @"执行任务失败后设定经过 X 时间后执行",
            [@"failure_interval_help"] = @"",
            [@"fallen_sun_config"] = @"日轮之陨",
            [@"find_dokan_refresh_count"] = @"道馆列表最大刷新次数",
            [@"find_dokan_refresh_count_help"] = @"单次查找道馆过程中，最大刷新次数。若超过此次数，会随机在当前显示的列表中(3-4个)选择系数最低的",
            [@"find_dokan_score"] = @"道馆系数",
            [@"find_earring"] = @"寻找耳环",
            [@"find_earring_help"] = @"300体力->金币28万",
            [@"find_jade_config"] = @"寻找协作配置",
            [@"find_mode"] = @"寻找队友模式",
            [@"find_mode_help"] = @"默认会从上方列表自动寻找 \n""好友"" -> ""最近"" -> ""寮友"" -> ""跨区""，当然建议选择‘recent_friend’这样会快点",
            [@"find_true_orochi"] = @"挑战御魂十层触发真蛇",
            [@"find_true_orochi_help"] = @"",
            [@"float_parade"] = @"花车巡游配置",
            [@"float_time"] = @"随机延迟时间",
            [@"float_time_help"] = @"防封，下次运行时间将在此范围内随机延迟，一般三五分钟即可。有强制执行时，确保不超出窗口：如麒麟19:00+2分钟，逢魔17:00+1.5小时，避免影响其他任务",
            [@"friend_1"] = @"第一个队友名字",
            [@"friend_2"] = @"第二个队友名字",
            [@"friend_2_name_help"] = @"同上",
            [@"friend_invitation"] = @"当出现协作邀请时",
            [@"friend_invitation_help"] = @"默认全部接受",
            [@"friend_love"] = @"友情点",
            [@"friend_name_help"] = @"输入队友的名字必须是全称，这一项是基于OCR来识别，如果名字过于离谱建议画200勾玉改一个正常点的名字",
            [@"friendship_points"] = @"[杂货铺]友情点购买",
            [@"frog_boss_config"] = @"对弈竞猜",
            [@"general_battle"] = @"通用战斗",
            [@"general_battle_config"] = @"通用战斗配置",
            [@"general_climb"] = @"通用爬塔",
            [@"general_combat_time"] = @"副将战斗时间",
            [@"gold_youkai"] = @"金币妖怪",
            [@"goryou_class"] = @"挑战类型",
            [@"goryou_class_help"] = @"",
            [@"goryou_config"] = @"御灵之境",
            [@"greed_maneki"] = @"贪吃鬼喂食+未升级的御魂奉纳",
            [@"greed_maneki_help"] = @"建议四星及以下的吃掉，五星的留给贪吃鬼",
            [@"green_enable"] = @"启用我方绿标",
            [@"green_enable_help"] = @"在战斗开始的一瞬间点击绿标，无反馈点击",
            [@"green_mark"] = @"设置第 X 个式神为绿标",
            [@"green_mark_help"] = @"可选[左一, 左二, 左三, 左四, 左五, 主阴阳师]",
            [@"green_mark_shikigami_name"] = @"式神名绿标",
            [@"green_mark_shikigami_name_help"] = @"根据式神自定义名称进行绿标，多个式神名可用英文逗号,分隔;",
            [@"group_name"] = @"御魂分组名",
            [@"guild_ap_enable"] = @"顺路收取寮补给",
            [@"guild_ap_enable_help"] = @"必选项",
            [@"guild_assets_enable"] = @"顺路收取寮资金",
            [@"guild_assets_enable_help"] = @"必选项",
            [@"guild_banquet_config"] = @"配置",
            [@"guild_banquet_time"] = @"寮宴会时间配置",
            [@"guild_store"] = @"[寮]功勋商店",
            [@"guild_wish"] = @"寮祈愿（还不知道可以写什么）",
            [@"handle"] = @"句柄 Handle",
            [@"handle_error"] = @"启用异常处理",
            [@"handle_error_help"] = @"处理部分异常，运行出错时撤退",
            [@"handle_help"] = @"填 ""auto"" 自动检测模拟器，多个模拟器正在运行或使用不支持自动检测的模拟器时无法使用 ""auto""，必须手动填写
输入为句柄标题或者是句柄号，每次启动模拟器时句柄号会变化。清空表示不使用window的操作方式。

句柄标题 Handle:
[MuMu模拟器12]: ""MuMu模拟器12""
[MuMu模拟器]: ""MuMu模拟器"" 
[雷电模拟器](全系列通用): ""雷电模拟器""

句柄号 Handle:
某些模拟器多开时具有相同的句柄标题（说的就是MuMu），此时需要手动获取模拟器的句柄号手动设置。
获取工具请查阅文档：[模拟器支持]",
            [@"harvest_config"] = @"收菜配置",
            [@"harvest_enable_help"] = @"这个一个部分是为了在登录游戏时，自动点击赠送的奖励，是必选项",
            [@"harvest_guild_max_times"] = @"收取寮资金或体力失败的最大尝试次数",
            [@"harvest_guild_max_times_help"] = @"默认3次",
            [@"harvest_soul"] = @"启用收获御魂",
            [@"herotest"] = @"英杰试炼",
            [@"high_bondling_discs"] = @"万象式盘",
            [@"high_bondling_discs_help"] = @"可选[0~50]",
            [@"home_client_clear"] = @"启用庭院客户端清空缓存",
            [@"home_client_clear_help"] = @"有时会出现进入庭院要求清理缓存",
            [@"honor_full_exit"] = @"刷满荣誉就退出",
            [@"honor_full_exit_help"] = @"这无需关心本周荣誉的上限是什么",
            [@"honor_room"] = @"[杂货铺]荣誉购买",
            [@"hunt_config"] = @"狩猎战",
            [@"hunt_time"] = @"狩猎战时间",
            [@"hya_auto_bean"] = @"自动切换豆子数量",
            [@"hya_auto_bean_help"] = @"默认全局十个豆子",
            [@"hya_control_method"] = @"撒豆过程的控制方式",
            [@"hya_g"] = @"G",
            [@"hya_g_help"] = @"呱太，单独从N卡分出来",
            [@"hya_info"] = @"显示更多日志",
            [@"hya_info_help"] = @"",
            [@"hya_interval"] = @"限制最短截屏时间",
            [@"hya_interval_help"] = @"单位ms， 最少100",
            [@"hya_invite_friend"] = @"是否邀请好友",
            [@"hya_invite_friend_help"] = @"",
            [@"hya_limit_count"] = @"百鬼砸 X 张票子",
            [@"hya_limit_count_help"] = @"",
            [@"hya_limit_time"] = @"限制任务百鬼执行时间",
            [@"hya_limit_time_help"] = @"",
            [@"hya_n"] = @"N",
            [@"hya_n_help"] = @"",
            [@"hya_priorities"] = @"最高优先级",
            [@"hya_priorities_help"] = @"正所谓我的代码在你之上，查阅文档找到对应的label，使用逗号分隔开",
            [@"hya_r"] = @"R",
            [@"hya_r_help"] = @"",
            [@"hya_save_result"] = @"保存每一次砸百鬼的最终收获",
            [@"hya_save_result_help"] = @"将会保存图片在""./log/hyakkiyakou""",
            [@"hya_screenshot"] = @"",
            [@"hya_screenshot_method"] = @"撒豆过程的截图方式",
            [@"hya_show"] = @"运行期间显示目标检测及跟踪",
            [@"hya_show_help"] = @"众所周知，开启额外的功能将会额外带来性能占用",
            [@"hya_sp"] = @"SP卡权重",
            [@"hya_sp_help"] = @"保持默认即可",
            [@"hya_sr"] = @"SR",
            [@"hya_sr_help"] = @"",
            [@"hya_ssr"] = @"SSR",
            [@"hya_ssr_help"] = @"",
            [@"hyakkiyakou_config"] = @"百鬼配置",
            [@"hyakkiyakou_models"] = @"模型设置",
            [@"ignore"] = @"全部忽略，对方无拒绝提示",
            [@"inference_engine"] = @"推理引擎",
            [@"inference_engine_help"] = @"使用CPU(Onnxruntime)还是GPU(TensorRT), TensorRT依赖Cuda环境，详情看文档",
            [@"initial_score"] = @"设置初始斗技分值",
            [@"initial_score_help"] = @"默认为8颗星之后每赢一场加100输一场减100",
            [@"interval"] = @"执行任务后设定经过 X 时间后执行",
            [@"interval_help"] = @"",
            [@"invitation_detect_interval"] = @"检测间隔",
            [@"invite_config"] = @"通用邀请配置",
            [@"invite_friend_name"] = @"协作任务邀请特定人员",
            [@"invite_friend_name_help"] = @"填写朋友昵称,无法区分不同服务器相同昵称好友, 仅单个好友",
            [@"invite_history_1"] = @"金协",
            [@"invite_history_1_help"] = @"上次被邀请（金币协作）的时间",
            [@"invite_history_2"] = @"勾协",
            [@"invite_history_2_help"] = @"上次被邀请（勾玉协作）的时间",
            [@"invite_history_4"] = @"粮协",
            [@"invite_history_4_help"] = @"上次被邀请（狗粮协作）的时间",
            [@"invite_history_8"] = @"体协",
            [@"invite_history_8_help"] = @"上次被邀请（体力协作）的时间",
            [@"invite_info_count"] = @"被邀请账号数量",
            [@"invite_info_count_help"] = @"此处填写被邀请账号数量，正整数，用于生成用于填写的配置列表。在此处填写数字后，切换到其他配置项（例如：探索、觉醒等），然后切换回来，会自动生成对应数量的配置项。",
            [@"invite_info_list_1"] = @"大号-1",
            [@"invite_info_list_2"] = @"大号-2",
            [@"invite_info_list_3"] = @"大号-3",
            [@"invite_info_list_4"] = @"大号-4",
            [@"invite_number"] = @"邀请人数",
            [@"invite_number_help"] = @"作为队长时有效，可选1或者2，为1时只会邀请第一个队友,",
            [@"iou_threshold"] = @"非极大值抑制(NMS)阈值",
            [@"iou_threshold_help"] = @"后处理技术，用于减少检测结果中的冗余框。当检测到多个重叠的框时，NMS选择一个最优的框，并抑制（去除）其他重叠度较高的框。",
            [@"jade_and_food"] = @"勾协+食协",
            [@"kirin_group_team"] = @"麒麟御魂切换",
            [@"kirin_time"] = @"麒麟时间",
            [@"kirin_type"] = @"麒麟选择",
            [@"kirin_type_help"] = @"",
            [@"kitty_attempts"] = @"运行次数",
            [@"kitty_attempts_help"] = @"",
            [@"kitty_quit_when_finished"] = @"达成目标后退出",
            [@"kitty_quit_when_finished_help"] = @"",
            [@"kitty_shop_config"] = @"猫咪铺子配置",
            [@"last_complete_time"] = @"上次登录时间",
            [@"last_complete_time_help"] = @"用于判断是否需要重新登录，",
            [@"layer"] = @"挑战层数",
            [@"layer_10"] = @"挑战十层",
            [@"layer_10_help"] = @"考虑到练度，这将不是默认打开的",
            [@"layer_9"] = @"挑战九层",
            [@"layer_help"] = @"",
            [@"level_reward"] = @"选择礼盒",
            [@"level_reward1"] = @"第一优先级收取的奖励",
            [@"level_reward2"] = @"第二优先级收取的奖励",
            [@"limit_count"] = @"限制挑战次数",
            [@"limit_count_help"] = @"两个限制需要同时设置，最先达到就会退出。建议执行时间设置成一个小时足够长，此时基于次数来判定设置为100次",
            [@"limit_time"] = @"限制运行时间",
            [@"limit_time_help"] = @"",
            [@"little_kuro_switch"] = @"设置小黑的御魂装配分组",
            [@"little_kuro_switch_help"] = @"",
            [@"lock_team_enable"] = @"锁定阵容",
            [@"lock_team_enable_help"] = @"如果锁定阵容将无法启用预设队伍、加成功能",
            [@"login_character_config"] = @"同一账号多个区服配置",
            [@"low_bondling_discs"] = @"百物式盘",
            [@"low_bondling_discs_special"] = @"契灵低级盘，可选[0~100]",
            [@"luck_msg"] = @"吉闻祝福",
            [@"md_default_strategy"] = @"默认策略",
            [@"md_match_names"] = @"匹配的鬼王全名",
            [@"md_preset_group_team_1"] = @"鬼王血量大于阈值时使用的预设阵容",
            [@"md_preset_group_team_2"] = @"鬼王血量小于阈值时使用的预设阵容",
            [@"md_preset_group_team_default_1"] = @"鬼王血量大于阈值时使用的预设阵容",
            [@"md_preset_group_team_default_1_help"] = @"选项格式: group,team, 比如3,2 \ngroup的值在[1~7]之间, team的值在[1~4]之间",
            [@"md_preset_group_team_default_2"] = @"鬼王血量小于阈值时使用的预设阵容",
            [@"md_preset_group_team_default_2_help"] = @"下面的预设阵容设置同理",
            [@"md_strategies_1"] = @"自定义策略组1",
            [@"md_strategies_10"] = @"自定义策略组10",
            [@"md_strategies_11"] = @"自定义策略组11",
            [@"md_strategies_12"] = @"自定义策略组12",
            [@"md_strategies_13"] = @"自定义策略组13",
            [@"md_strategies_14"] = @"自定义策略组14",
            [@"md_strategies_15"] = @"自定义策略组15",
            [@"md_strategies_16"] = @"自定义策略组16",
            [@"md_strategies_17"] = @"自定义策略组17",
            [@"md_strategies_18"] = @"自定义策略组18",
            [@"md_strategies_19"] = @"自定义策略组19",
            [@"md_strategies_2"] = @"自定义策略组2",
            [@"md_strategies_20"] = @"自定义策略组20",
            [@"md_strategies_21"] = @"自定义策略组21",
            [@"md_strategies_22"] = @"自定义策略组22",
            [@"md_strategies_23"] = @"自定义策略组23",
            [@"md_strategies_24"] = @"自定义策略组24",
            [@"md_strategies_25"] = @"自定义策略组25",
            [@"md_strategies_26"] = @"自定义策略组26",
            [@"md_strategies_27"] = @"自定义策略组27",
            [@"md_strategies_28"] = @"自定义策略组28",
            [@"md_strategies_29"] = @"自定义策略组29",
            [@"md_strategies_3"] = @"自定义策略组3",
            [@"md_strategies_30"] = @"自定义策略组30",
            [@"md_strategies_31"] = @"自定义策略组31",
            [@"md_strategies_32"] = @"自定义策略组32",
            [@"md_strategies_33"] = @"自定义策略组33",
            [@"md_strategies_4"] = @"自定义策略组4",
            [@"md_strategies_5"] = @"自定义策略组5",
            [@"md_strategies_6"] = @"自定义策略组6",
            [@"md_strategies_7"] = @"自定义策略组7",
            [@"md_strategies_8"] = @"自定义策略组8",
            [@"md_strategies_9"] = @"自定义策略组9",
            [@"md_strategy_count"] = @"策略组数量",
            [@"md_strategy_count_help"] = @"设置后，切换别的设置然后切换回来就会显示全部策略， 不要设置为负值",
            [@"md_use_strategy"] = @"开启策略组模式",
            [@"md_use_strategy_help"] = @"没有开启时任务全程不会切换预设阵容 \n开启后会根据策略组在战斗准备阶段切换出战阵容(后面加别的功能) \n\n第一次战斗的时候如果是1~4星鬼王, 会切换一次默认预设阵容 \n如果鬼王是5/6高星, 每一次战斗准备阶段根据鬼王血量和策略组设置来换阵容\n如果没有匹配的鬼王时使用默认策略  \n\n注: 鬼王血量阈值大概是35%  \n匹配的鬼王全名需要和游戏界面上显示的一致, 不能是缩写 每一组可以匹配多个鬼王中间用逗号分隔开 举个例子： 妙主九命猫,御撰津 \n推荐开启消息推送,在脚本->脚本->出错设置中配置,当寻找到5/6星鬼王的时候推送通知",
            [@"medal_room"] = @"[杂货铺]勋章购买",
            [@"medium_bondling_discs"] = @"千咒式盘",
            [@"medium_bondling_discs_help"] = @"可选[0~20]",
            [@"medium_bondling_discs_special"] = @"契灵中级盘，可选[0~100]",
            [@"memory_scrolls_config"] = @"绘卷配置",
            [@"memory_scrolls_finish"] = @"绘卷结束配置",
            [@"meta_crafting_card"] = @"自动合成高星召唤卡",
            [@"meta_demon_config"] = @"超鬼王配置",
            [@"min_bounty"] = @"最少赏金",
            [@"min_bounty_help"] = @"开启道馆的最少赏金",
            [@"min_people_num"] = @"最少人数",
            [@"min_people_num_help"] = @"开启道馆的最少人数",
            [@"minions_cnt"] = @"打 X 只怪后结束任务",
            [@"minions_cnt_help"] = @"软计数",
            [@"missions_config"] = @"集体任务",
            [@"missions_rule"] = @"任务选择优先级",
            [@"missions_rule_help"] = @"",
            [@"missions_select"] = @"指定任务",
            [@"miyoshino"] = @"接送弥助",
            [@"miyoshino_help"] = @"100体力->三星结界卡",
            [@"miyoshino_painting"] = @"弥助的画",
            [@"miyoshino_painting_help"] = @"300体力->六星变异卡",
            [@"model_precision"] = @"模型精度",
            [@"model_precision_help"] = @"32位浮点型和8位整形，后者使用精度换取速度，大约有1~4倍的提速(看机器)",
            [@"monday_to_thursday"] = @"周一到周四",
            [@"monday_to_thursday_help"] = @"是否只在周一到周四开启道馆",
            [@"mystery_amulet"] = @"神秘咒符",
            [@"mystery_amulet_help_honor"] = @"默认买两个",
            [@"name"] = @"角色名",
            [@"name_help"] = @"庭院左上角显示的那个",
            [@"netherworld_group_team"] = @"阴界之门御魂切换",
            [@"netherworld_time"] = @"阴界之门时间",
            [@"next_exploration_time"] = @"下次探索时间",
            [@"next_run"] = @"下一次运行时间",
            [@"next_run_help"] = @"会根据下面的间隔时间自动计算时间",
            [@"next_ryoutoppa_time"] = @"下一次寮突破时间",
            [@"nian_config"] = @"年兽配置",
            [@"notification_95"] = @"95%进度通知",
            [@"notify_config"] = @"消息推送配置",
            [@"notify_config_help"] = @"输入为yaml格式，"":""冒号后有一个空格，具体请翻阅文档[消息推送]",
            [@"notify_enable"] = @"启用消息推送",
            [@"number_attack"] = @"挑战次数",
            [@"number_attack_help"] = @"默认30，可选范围[1~30]，没有挑战卷自动退出任务（标记为成功）",
            [@"number_base"] = @"突破卷数量大于等于 X 时才会挑战",
            [@"number_base_help"] = @"旨在检查突破卷数量，如果当前的数量没有大于等于这个值，将标记为成功并退出， 可选值[0~20]",
            [@"one_summon"] = @"每日召唤",
            [@"only_jade"] = @"仅勾玉",
            [@"optimization"] = @"优化设置",
            [@"order_attack"] = @"挑战顺序",
            [@"order_attack_help"] = @"使用过滤器，保持默认即可",
            [@"orochi_config"] = @"副本设置",
            [@"orochi_scales"] = @"朴素御魂",
            [@"orochi_scales_help"] = @"可选[0~40]",
            [@"package_name"] = @"游戏客户端",
            [@"package_name_help"] = @"模拟器上装有多个游戏客户端时，需要手动选择服务器",
            [@"pass_limit"] = @"",
            [@"pass_limit_help"] = @"",
            [@"password"] = @"password",
            [@"password_help"] = @"",
            [@"pets_config"] = @"小猫咪",
            [@"pets_feast"] = @"饕餮大餐",
            [@"pets_happy"] = @"其乐融融",
            [@"picture_book_rule"] = @"选择御魂优先级",
            [@"picture_book_rule_help"] = @"使用auto即可",
            [@"picture_book_scrap"] = @"海汐御魂",
            [@"picture_book_scrap_help"] = @"可选[0~30]",
            [@"port"] = @"port",
            [@"port_help"] = @"",
            [@"preset_enable"] = @"启用切换预设队伍",
            [@"preset_enable_help"] = @"将会在第一次战斗的时候切换队伍预设",
            [@"preset_group"] = @"第 X 个预设组",
            [@"preset_group_1"] = @"馆员阵容",
            [@"preset_group_1_help"] = @"打除馆主外的人时，使用的阵容,格式：3,2 ,表示第三组，第二个队伍,取值范围与其他设置预设队伍相同",
            [@"preset_group_2"] = @"馆主阵容",
            [@"preset_group_2_help"] = @"打馆主时使用的阵容,格式同上",
            [@"preset_group_help"] = @"可选[1~7]",
            [@"preset_team"] = @"第 X 个预设队伍",
            [@"preset_team_help"] = @"可选[1~5]",
            [@"priority"] = @"任务优先级",
            [@"priority_help"] = @"如果设置调度规则为基于优先级，则该选项有效，默认为5，数字越低优先级越高，可取[1~15],如果同优先级,则按照先来后到规则进行调度",
            [@"quiz_cnt"] = @"答题多少轮",
            [@"quiz_cnt_help"] = @"",
            [@"quiz_config"] = @"答题配置",
            [@"quiz_per_round"] = @"每轮计划答多少道题",
            [@"quiz_per_round_help"] = @"",
            [@"raid_config"] = @"突破配置",
            [@"random_click_swipt_enable"] = @"战斗时随机点击或者随机滑动",
            [@"random_click_swipt_enable_help"] = @"防封优化，每三分钟的战斗可能触发0~8次，请注意这个与绿标功能冲突，可能会乱点绿标",
            [@"random_delay"] = @"随机延迟",
            [@"random_delay_help"] = @"正式进攻会设定 2s - 10s 的随机延迟，避免攻击间隔极其相近被检测为脚本。",
            [@"random_sleep"] = @"随机休息",
            [@"random_soul"] = @"随机御魂",
            [@"random_soul_help"] = @"可选[0~100]",
            [@"red_daruma"] = @"招福达摩",
            [@"reject"] = @"全部拒绝，对方有拒绝提示",
            [@"remain_attack_count"] = @"剩余攻击次数",
            [@"remain_attack_count_help"] = @"用于记录当前剩余攻击次数。一般情况下，此值无须手动修改",
            [@"reset_task_datetime"] = @"重设的时间",
            [@"reset_task_datetime_enable"] = @"重置所有任务的下一次运行时间",
            [@"reset_task_datetime_enable_help"] = @"勾选立即执行，记得反选掉",
            [@"rest_task_datetime_help"] = @"",
            [@"reward_floor"] = @"悬赏鬼王星级",
            [@"reward_floor_help"] = @"默认打较简单的一星鬼王，若想要更高悬赏奖励可自行更改为十星或不更改（保留已勾选DEBUFF）",
            [@"run_background_only"] = @"启用模拟器仅后台运行",
            [@"run_sequence"] = @"运行爬塔顺序",
            [@"run_sequence_help"] = @"pass:门票,ap100:100体,boss:boss战,ap:体力 \n英文逗号分隔,从左到右运行,可自定义执行顺序 \n例如:pass,ap100,boss,ap就是门票->100体->boss战->体力",
            [@"ryou_access"] = @"寮管理开启寮突破",
            [@"ryou_access_help"] = @"",
            [@"save_error"] = @"出错时，保存 Log 和截图",
            [@"scales"] = @"御魂礼盒",
            [@"schedule_rule"] = @"选择任务调度规则",
            [@"schedule_rule_help"] = @"这里所指的调度的对象是指Pending中的，Waiting中的任务不属于。
基于过滤器(Filter)的调度：默认的选项，任务的执行顺序会根据开发时所确定的顺序来调度，一般是最优解
基于先来后到(FIFO)的调度：是会按照下次执行时间进行排序，靠前的先执行
基于优先级(Priority)的调度：高优先级先于低优先级执行，同优先级按照先来后到顺序",
            [@"scheduler"] = @"调度器",
            [@"screenshot_interval"] = @"放慢截图速度至 X 秒一张",
            [@"screenshot_interval_help"] = @"执行两次截图之间的最小间隔，限制在 0.1 ~ 0.3，对于高配置电脑能降低 CPU 占用",
            [@"screenshot_length"] = @"出错时，保留最后 X 张截图",
            [@"screenshot_method"] = @"模拟器截屏方案",
            [@"screenshot_method_help"] = @"使用自动选择时，将执行一次性能测试并自动更改为最快的截图方案。一般情况下的速度: 
window_background ~= nemu_ipc >>> DroidCast_raw >  ADB_nc >> DroidCast > uiautomator2 ~= ADB
使用window_background来截图是10ms左右，对比DroidCast_raw是100ms左右（仅限作者的电脑）。但是window_background有一个致命的缺点是模拟器不可以最小化，
nemu_ipc仅限mumu12模拟器且要求版本大于3.8.13，并且需要设置模拟器的执行路径",
            [@"scroll_number"] = @"绘卷序号",
            [@"scroll_number_help"] = @"选择你需要捐献的绘卷序号,顺序按照从左往右从上往下排列",
            [@"scrolls"] = @"绘卷模式",
            [@"scrolls_cd"] = @"间隔时间",
            [@"scrolls_cd_help"] = @"将接管探索任务的调度器设置下一次的执行时间",
            [@"scrolls_enable"] = @"绘卷模式功能",
            [@"scrolls_enable_help"] = @"",
            [@"scrolls_threshold"] = @"超过 X 张突破卷将切换任务",
            [@"scrolls_threshold_help"] = @"探索模式运行中检测突破卷数量，超过该数量将结束探索任务并唤起突破任务",
            [@"secret_config"] = @"秘闻副本",
            [@"secret_gold_100"] = @"金币加成100%",
            [@"secret_gold_100_help"] = @"同上",
            [@"secret_gold_50"] = @"金币加成50%",
            [@"secret_gold_50_help"] = @"这将会在低层[1-5]自动打开加成并且自动关闭加成",
            [@"select_friend_list"] = @"选择同区还是跨区好友",
            [@"select_friend_list_help"] = @"",
            [@"serial"] = @"模拟器 Serial",
            [@"serial_help"] = @"常见的模拟器 Serial 可以查询下方列表
填 ""auto"" 自动检测模拟器，多个模拟器正在运行或使用不支持自动检测的模拟器时无法使用 ""auto""，必须手动填写

模拟器默认 Serial:
[MuMu模拟器12]: 127.0.0.1:16384 
[MuMu模拟器]: 127.0.0.1:7555 
[雷电模拟器](全系列通用): emulator-5554 或 127.0.0.1:5555

如果没有提及的那可能是还没有测试或者不推荐使用，可以自行尝试
如果你使用了模拟器的多开功能，它们的 Serial 将不是默认的，可以在 console.bat 中执行 `adb devices` 查询，或根据模拟器官方的教程填写",
            [@"server_update"] = @"强制设定服务执行时间",
            [@"server_update_help"] = @"如果设定不是默认的 ""09:00:00"",该任务每次执行完毕后会强制设定下次运行时间为第二天的设定值",
            [@"setup_when_bondling"] = @"执行契灵任务是唤起",
            [@"setup_when_bondling_help"] = @"",
            [@"share_area_boss"] = @"地鬼分享",
            [@"share_area_boss_help"] = @"没什么建议，勾上就对了",
            [@"share_collect"] = @"图鉴分享",
            [@"share_collect_help"] = @"每周一张票、不要白不要",
            [@"share_config"] = @"分享配置",
            [@"share_friend_1"] = @"第一个好友名字",
            [@"share_friend_1_help"] = @"使用OCR来识别，留空表示不使用",
            [@"share_friend_2"] = @"第二个好友名字",
            [@"share_friend_3"] = @"第三个好友名字",
            [@"share_friend_4"] = @"第四个好友名字",
            [@"share_friend_5"] = @"第五个好友名字",
            [@"share_secret"] = @"秘闻分享",
            [@"share_secret_help"] = @"建议在秘闻结束后再来执行这个任务",
            [@"shikigami_class"] = @"寄养式神类型",
            [@"shikigami_class_help"] = @"选择的式神类别（寄养默认选择N卡，且不建议选别的）",
            [@"shikigami_order"] = @"选中第几个式神寄养",
            [@"shikigami_order_help"] = @"从左开始选第几个式神",
            [@"shop_config"] = @"购买",
            [@"shop_kaiko_3"] = @"三星太鼓",
            [@"shop_kaiko_4"] = @"四星太鼓",
            [@"shrine"] = @"神龛",
            [@"simple_tidy"] = @"简易御魂清理",
            [@"six_realms_gate"] = @"六道之门配置",
            [@"skin_ticket"] = @"皮肤券",
            [@"skin_ticket_help"] = @"可选[0~5]",
            [@"skip_difficult"] = @"跳过难度较高的结界",
            [@"skip_difficult_help"] = @"失败后不再攻打该结界",
            [@"snowball_switch"] = @"设置茨球的御魂装配分组",
            [@"snowball_switch_help"] = @"",
            [@"sougenbi_class"] = @"挑战类型",
            [@"sougenbi_config"] = @"业原火配置",
            [@"soul_buff_enable"] = @"开启御魂加成",
            [@"soul_buff_enable_help"] = @"会在庭院开始的时候设置加成",
            [@"special_room"] = @"[杂货铺]特殊购买",
            [@"store_sign"] = @"商店签到",
            [@"store_sign_help"] = @"就那个签到50次得黑蛋的",
            [@"strange_trace"] = @"奇怪的痕迹",
            [@"strange_trace_help"] = @"100体力->金币九万八",
            [@"strategy_frog"] = @"下注策略",
            [@"strategy_frog_help"] = @"",
            [@"success_interval"] = @"执行任务成功后设定经过 X 时间后执行",
            [@"success_interval_help"] = @"",
            [@"summon_type"] = @"召唤类型",
            [@"sup_account_count"] = @"小号账号数量",
            [@"sup_account_count_help"] = @"仅支持官服，渠道服无法使用。同上。更多详情见代码目录tasks/FindJade/README.md",
            [@"sup_account_list_1"] = @"小号-1",
            [@"sup_account_list_10"] = @"小号-10",
            [@"sup_account_list_11"] = @"小号-11",
            [@"sup_account_list_12"] = @"小号-12",
            [@"sup_account_list_13"] = @"小号-13",
            [@"sup_account_list_14"] = @"小号-14",
            [@"sup_account_list_15"] = @"小号-15",
            [@"sup_account_list_16"] = @"小号-16",
            [@"sup_account_list_17"] = @"小号-17",
            [@"sup_account_list_18"] = @"小号-18",
            [@"sup_account_list_19"] = @"小号-19",
            [@"sup_account_list_2"] = @"小号-2",
            [@"sup_account_list_20"] = @"小号-20",
            [@"sup_account_list_21"] = @"小号-21",
            [@"sup_account_list_22"] = @"小号-22",
            [@"sup_account_list_23"] = @"小号-23",
            [@"sup_account_list_24"] = @"小号-24",
            [@"sup_account_list_25"] = @"小号-25",
            [@"sup_account_list_26"] = @"小号-26",
            [@"sup_account_list_27"] = @"小号-27",
            [@"sup_account_list_28"] = @"小号-28",
            [@"sup_account_list_29"] = @"小号-29",
            [@"sup_account_list_3"] = @"小号-3",
            [@"sup_account_list_30"] = @"小号-30",
            [@"sup_account_list_31"] = @"小号-31",
            [@"sup_account_list_32"] = @"小号-32",
            [@"sup_account_list_33"] = @"小号-33",
            [@"sup_account_list_34"] = @"小号-34",
            [@"sup_account_list_35"] = @"小号-35",
            [@"sup_account_list_36"] = @"小号-36",
            [@"sup_account_list_37"] = @"小号-37",
            [@"sup_account_list_38"] = @"小号-38",
            [@"sup_account_list_39"] = @"小号-39",
            [@"sup_account_list_4"] = @"小号-4",
            [@"sup_account_list_40"] = @"小号-40",
            [@"sup_account_list_41"] = @"小号-41",
            [@"sup_account_list_42"] = @"小号-42",
            [@"sup_account_list_43"] = @"小号-43",
            [@"sup_account_list_44"] = @"小号-44",
            [@"sup_account_list_45"] = @"小号-45",
            [@"sup_account_list_46"] = @"小号-46",
            [@"sup_account_list_47"] = @"小号-47",
            [@"sup_account_list_48"] = @"小号-48",
            [@"sup_account_list_49"] = @"小号-49",
            [@"sup_account_list_5"] = @"小号-5",
            [@"sup_account_list_50"] = @"小号-50",
            [@"sup_account_list_6"] = @"小号-6",
            [@"sup_account_list_7"] = @"小号-7",
            [@"sup_account_list_8"] = @"小号-8",
            [@"sup_account_list_9"] = @"小号-9",
            [@"svr"] = @"服务器",
            [@"svr_help"] = @"服务器名，例如春之樱，乾坤行之类的。只有在找不到角色名时才会用到。同样，鉴于文字识别。。。，另外代码中做了模糊匹配，字数匹配达到50%，就算那个服务器",
            [@"switch_all_soul"] = @"一键切换斗技御魂",
            [@"switch_all_soul_help"] = @"你应当先进行式神御魂的导入",
            [@"switch_group_team"] = @"御魂装配分组设置",
            [@"switch_group_team_help"] = @"",
            [@"switch_preset_enable"] = @"开启切换预设队伍",
            [@"switch_preset_enable_help"] = @"不建议使用通用战斗设置中的切换预设队伍",
            [@"switch_soul"] = @"执行任务前切换御魂",
            [@"switch_soul_config"] = @"执行任务前切换御魂",
            [@"switch_soul_config_1"] = @"队伍1切换御魂配置",
            [@"switch_soul_config_2"] = @"队伍2切换御魂配置",
            [@"tako_config"] = @"石距",
            [@"talisman"] = @"花合战",
            [@"target_score"] = @"达到 X 分数后会结束任务",
            [@"target_score_help"] = @"3000以上表示为名士（也是自动斗技的最高）",
            [@"task_hoarding_duration"] = @"囤积任务 X 分钟",
            [@"tasks_config_reset"] = @"重置所有计划任务",
            [@"team_flow"] = @"team_flow",
            [@"team_name"] = @"队伍名",
            [@"ten_switch"] = @"十层御魂配置",
            [@"ten_switch_help"] = @"基于数字索引",
            [@"thousand_things"] = @"千物宝箱",
            [@"three_refresh"] = @"每三次就刷新",
            [@"three_refresh_help"] = @"挑战进度到三，领取奖励后就刷新，如果刷新操作进入CD，将标记为失败并退出",
            [@"time_of_mystery"] = @"强制设定出现神秘商店当天的执行时间",
            [@"time_of_mystery_help"] = @"限定[00:00:01-23:30:00],这将使你无视掉调度器的Interval。保持默认[00:00:00]表示不使用",
            [@"tomb_guard_switch"] = @"设置镇墓兽的御魂装配分组",
            [@"tomb_guard_switch_help"] = @"",
            [@"totem_pass"] = @"御灵券(40张)",
            [@"transport"] = @"transport",
            [@"transport_help"] = @"",
            [@"trifles"] = @"每周必选",
            [@"trifles_broken_amulet_help"] = @"建议设置较大的数值以每周清空",
            [@"trifles_config"] = @"每日琐事",
            [@"true_orochi_config"] = @"真蛇配置",
            [@"try_start_dokan"] = @"尝试开启道馆",
            [@"try_start_dokan_help"] = @"在道馆未开启状态下，是否查找道馆并开启。没有权限不建议开启",
            [@"twelve_switch"] = @"十二层御魂配置",
            [@"twelve_switch_help"] = @"基于数字索引，神罚",
            [@"unwanted_boss_name_help"] = @"英文逗号分隔鬼王名称, 示例: 酒吞童子,阎魔",
            [@"unwanted_boss_names"] = @"不想挑战的鬼王名称列表",
            [@"up_all"] = @"全部",
            [@"up_coin"] = @"金币",
            [@"up_daruma"] = @"达摩",
            [@"up_exp"] = @"经验",
            [@"up_type"] = @"选择UP类型",
            [@"up_type_help"] = @"",
            [@"use_collect"] = @"使用收藏的鬼王",
            [@"use_collect_help"] = @"",
            [@"user_status"] = @"身份",
            [@"user_status_help"] = @"可选队长、队员、单独刷（野队还不打算实现）",
            [@"user_status_help_"] = @"",
            [@"username"] = @"username",
            [@"username_help"] = @"",
            [@"utilize_config"] = @"结界蹭卡配置",
            [@"utilize_rule"] = @"寄养规则",
            [@"utilize_rule_help"] = @"挑选结界卡的规则，使用默认default即可，具体规则看文档[任务列表]，不可以选auto,已经弃置了。",
            [@"wait_time"] = @"等待时间",
            [@"wait_time_help"] = @"保持默认一分钟就好，期间每隔20s邀请一次",
            [@"wanted_quests_config"] = @"悬赏封印",
            [@"when_attack_fail"] = @"挑战失败时",
            [@"when_attack_fail_help"] = @"",
            [@"when_network_abnormal"] = @"当网络异常时",
            [@"when_network_abnormal_help"] = @"默认会先等待10S",
            [@"when_network_error"] = @"当网络出错需要重新连接服务器时",
            [@"when_network_error_help"] = @"重启游戏",
            [@"when_task_queue_empty"] = @"当任务队列清空后",
            [@"when_task_queue_empty_help"] = @"无任务时关闭游戏，能在收菜期间降低 CPU 占用",
            [@"white_daruma"] = @"奉为达摩",
            [@"white_daruma_five"] = @"五星白蛋",
            [@"white_daruma_four"] = @"四星白蛋",
            [@"zh-CN"] = @"简体中文",
        };

        private static readonly Dictionary<string, string> _builtInEnUs = new()
        {
            [@"Config update tip"] = @"The current script is running, please stop it before making modifications.",
            [@"Install OAS from local"] = @"This will download and decompress from Github. Please maintain a stable network connection. At the same time, this directory will be cleared",
            [@"Log out"] = @"Logout",
            [@"Notify Help"] = @"Please refer to the documentation [Message Push] to fill in the relevant configuration",
            [@"Project Statement"] = @"Open Source Software",
            [@"Service root path help"] = @"OASX and OAS are two different things. Do not confuse them, do not put them in the same directory, do not use spaces, do not use Chinese characters, and do not use overly long paths",
            [@"Task Setting"] = @"Settings",
            [@"accept_invitation_complete_now_help"] = @"To prevent cancellation by the other party due to two hours of inactivity, it is enabled by default",
            [@"adb_restart_help"] = @"",
            [@"broker_help"] = @"",
            [@"ca_help"] = @"",
            [@"control_method_help"] = @"Speed: window_message ~= minitouch > Hermit >>> uiautomator2 ~= ADB 
The control method simulates human speed, and faster is not always better. Using (window_message) may occasionally fail",
            [@"costume_battle_1"] = @"Realm of Melodies",
            [@"costume_main"] = @"On Tranquil Views",
            [@"costume_main_1"] = @"Celestial Garden",
            [@"costume_main_2"] = @"Luminescent Night",
            [@"costume_main_3"] = @"Melodic Pavilion",
            [@"costume_main_4"] = @"Painted Panorama",
            [@"costume_main_5"] = @"Autumn Maples",
            [@"costume_main_6"] = @"Hot Spring",
            [@"costume_main_7"] = @"Summer Nights",
            [@"costume_main_8"] = @"Far-sailing Ship",
            [@"costume_realm_1"] = @"Demon Spirit Charms",
            [@"costume_realm_2"] = @"Fox\'s Defensive Realm",
            [@"costume_realm_3"] = @"Threaded Memories",
            [@"costume_realm_4"] = @"Sea of Flowers",
            [@"costume_realm_default"] = @"Umbrella Sanctuary",
            [@"default_invite_help"] = @"",
            [@"delay_date_help"] = @"When the forced execution time is enabled above, customize how many days later to enforce execution. By default, it\'s one day later, meaning the next day",
            [@"emulatorinfo_name_help"] = @"Example: MuMuPlayer-12.0-0, if unclear, please consult the documentation",
            [@"emulatorinfo_path_help"] = @"Example: ""E:\\ProgramFiles\\MuMuPlayer-12.0\\shell\\MuMuPlayer.exe""",
            [@"emulatorinfo_type_help"] = @"Select the type of emulator you are using",
            [@"en-US"] = @"English",
            [@"enable_help"] = @"Add this task to the scheduler",
            [@"enable_switch_by_name_help"] = @"This is another way to switch souls. Compared to the method above, it supports more presets, but similarly, you still need to ensure that the preset team is in a locked state",
            [@"failure_interval_help"] = @"",
            [@"find_mode_help"] = @"By default, it will automatically search from the list above: \n""Friend"" -> ""Recent"" -> ""Guildmate"" -> ""Cross-server"". Of course, it is recommended to select ‘recent_friend’ as this will be faster",
            [@"float_time_help"] = @"To prevent account suspension, the next run time will be randomly delayed within this range; generally, three to five minutes is sufficient. When forced execution is enabled, ensure it does not exceed the window: for example, Kirin at 19:00 + 2 minutes, Demon Encounter at 17:00 + 1.5 hours, to avoid affecting other tasks",
            [@"friend_2_name_help"] = @"Same as above",
            [@"friend_invitation_help"] = @"Accept all by default",
            [@"friend_name_help"] = @"When inputting your teammate\'s name, it must be the full name. This is based on OCR recognition, so if the name is too unusual, it\'s recommended to spend 200 Jade to change it to something more standard",
            [@"green_enable_help"] = @"Click the green mark at the moment the battle starts, with no feedback on the click",
            [@"green_mark_help"] = @"Select from [Left 1, Left 2, Left 3, Left 4, Left 5, Main Onmyoji]",
            [@"handle_help"] = @"Fill in ""auto"" to automatically detect the emulator. ""auto"" cannot be used when multiple emulators are running or when using an emulator that does not support automatic detection; it must be filled in manually. The input is the handle title or handle number. The handle number changes each time the emulator is started. Clearing it means not using the window operation method.

Handle Title: 
[MuMu Player 12]: ""MuMu Player 12"" 
[MuMu Player]: ""MuMu Player"" 
[LDPlayer](all series): ""LDPlayer""

Handle Number: 
Some emulators have the same handle title when multiple instances are opened (referring to MuMu). In this case, you need to manually obtain the emulator's handle number and set it manually. 
Please refer to the documentation for tools to obtain it: [Emulator Support]",
            [@"harvest_enable_help"] = @"This section is for automatically clicking on login rewards when logging into the game. It is a required option",
            [@"home_client_clear_help"] = @"Sometimes it may require clearing the cache when entering the courtyard",
            [@"invite_number_help"] = @"This is effective when you are the team leader. You can choose 1 or 2. If you choose 1, only the first teammate will be invited",
            [@"lock_team_enable_help"] = @"If the team is locked, preset teams and buff features cannot be enabled",
            [@"next_run_help"] = @"The time will be automatically calculated based on the interval below",
            [@"notify_config_help"] = @"Input is in YAML format, there is a space after the colon "":"", for details please refer to the documentation [Message Push]",
            [@"package_name_help"] = @"When multiple game clients are installed on the emulator, you need to manually select the server",
            [@"password_help"] = @"",
            [@"port_help"] = @"",
            [@"preset_enable_help"] = @"The team preset will be switched during the first battle",
            [@"preset_group_help"] = @"Select[1~7]",
            [@"preset_team_help"] = @"Select[1~5]",
            [@"priority_help"] = @"This option is valid if the scheduling rule is set to priority-based. The default is 5. The lower the number, the higher the priority. The range is [1-15]. If the priority is the same, tasks are scheduled on a first-come, first-served basis",
            [@"random_click_swipt_enable_help"] = @"Anti-blocking optimization: may trigger 0-8 times in every three minutes of battle. Please note that this conflicts with the green mark function and may cause random clicks on the green mark",
            [@"rest_task_datetime_help"] = @"",
            [@"schedule_rule_help"] = @"The scheduling objects referred to here are those in Pending; tasks in Waiting are not included. 
Filter-based scheduling: The default option. The execution order of tasks will be scheduled according to the order determined during development, which is generally the optimal solution. 
First-In, First-Out (FIFO)-based scheduling: Tasks will be sorted by their next execution time, and those at the front will be executed first. 
Priority-based scheduling: High-priority tasks are executed before low-priority tasks. Tasks with the same priority are executed in a first-come, first-served order",
            [@"screenshot_interval_help"] = @"The minimum interval between two screenshots, limited to 0.1 ~ 0.3, can reduce CPU usage for high-configuration computers",
            [@"screenshot_method_help"] = @"When automatic selection is used, a performance test will be performed once, and it will automatically change to the fastest screenshot solution. The general speed is: 
window_background ~= nemu_ipc >>> DroidCast_raw > ADB_nc >> DroidCast > uiautomator2 ~= ADB 
Using window_background for screenshots is about 10ms, compared to DroidCast_raw which is about 100ms (only on the author's computer). However, window_background has a fatal flaw: the emulator cannot be minimized. 
nemu_ipc is limited to MuMu Player 12 and requires a version greater than 3.8.13, and the emulator's execution path needs to be set",
            [@"serial_help"] = @"Common emulator serials can be found in the list below. 
Fill in ""auto"" to automatically detect the emulator. When multiple emulators are running or an emulator that does not support automatic detection is used, ""auto"" cannot be used and must be filled in manually.
  
Default emulator serials: 
[MuMu Player 12]: 127.0.0.1:16384 
[MuMu Player]: 127.0.0.1:7555 
[LDPlayer](all series): emulator-5554 or 127.0.0.1:5555
If it's not mentioned, it may not have been tested or is not recommended. You can try it yourself. 
If you use the multi-instance function of the emulator, their serials will not be the default. You can query them by executing adb devices in console.bat, or fill them in according to the official emulator tutorial",
            [@"server_update_help"] = @"If it's not set to the default ""09:00:00"", the task will forcibly set the next run time to the set value of the next day after each execution",
            [@"success_interval_help"] = @"",
            [@"switch_group_team_help"] = @"",
            [@"transport_help"] = @"",
            [@"username_help"] = @"",
            [@"wait_time_help"] = @"Keep the default setting for one minute, and invite once every 20 seconds during this period",
            [@"when_network_abnormal_help"] = @"By default, it will wait for 10 seconds first",
            [@"when_network_error_help"] = @"Restart the game",
            [@"when_task_queue_empty_help"] = @"Close the game when there are no tasks, which can reduce CPU usage during farming periods",
            [@"zh-CN"] = @"简体中文",
        };
}
